apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.keptn-delivery-dev.34.70.87.241.nip.io
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice.keptn-delivery-dev.svc.cluster.local
